[project]
authors = ["boray"]
entry = "main.sw"
license = "Apache-2.0"
name = "harberger-ownership"

[constants]
BASE_FEE = { type = "u64", value = "200" }
ONE_DAY = { type = "u64", value = "86400000" }
ONE_MONTH = { type = "u64", value = "2629800000" }
ONE_WEEK = { type = "u64", value = "604800000" }
ONE_YEAR = { type = "u64", value = "31556952000" }
TAX_RATIO = { type = "u64", value = "10" }


[dependencies]
