[project]
authors = ["boray"]
entry = "main.sw"
license = "Apache-2.0"
name = "harberger-ownership"

[constants]
base_fee = { type = "u64", value = "200" }
tax_ratio = { type = "u64", value = "10" } 


[dependencies]
